version: 2.1

orbs:
  maven: circleci/maven@1.0.0

jobs:
  depedency-fix:
    executor:
      name: maven/default
    steps:
      - maven/with_cache:
          maven_command: mvn compile
          steps:
            - run: mvn compile
            - run: mvn install -DskipTests

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
