version: 2.1

orbs:
  maven: circleci/maven@1.0.0

jobs:
  dependency-fix:
    executor: maven/default
    steps:
      - run: ls -l
      - run: mvn install -DskipTests

workflows:
  maven_test:
    jobs:
      - dependency-fix
      - maven/test # checkout, build, test, and upload test results
